### ISSUE TITLE
Kernel dying

### ISSUE THREAD

**Issue by cschwem2er** [jrfiedler/stata-kernel#1]
Hi, 

thank you very much for this attempt to finally level up Stata "Do-Files" ;) I remember you also wrote a python package for Stata.

Unfortunately your version does not work for me at the moment. I can select the Stata kernel, but it dies as soon as the notebook opens and tries to load the Kernel. I tried this with iPython 3.2 and 4.0, my Stata Version is MP14 (x64). I also doubled checked my Automation object, which works just fine for ipystata.

Update: The problem was pretty simple: Python 3 incompatibility due to missing parentheses for a print statement. I sent you a pull request with the change and an updated source for the kernelbase import.

**Comment by jhconning** [comment]
I'm also having trouble on a Windows 64 machine with Stata 11 IC.  The sample notebook loads in the browser but within a few seconds I have a dead kernel.   Could it be that the kernel has to be adapted to the version of Stata?   What setup(s) has this been tested under?

UPDATE: I've now got it working!
In case it's of use to other relative newbies like myself, this is how I got it to work: 
1. Clone the github repo to your machine. _Until his pull request is accepted_, use @methodds fork as it contains his [suggested patch](https://github.com/methodds/stata-kernel/blob/methodds-patch-1/stata_kernel/stata_kernel.py) to work with python3 (and I believe if you also add the line

```
 from __future__ import print_function 
```

to the top of the stata_kernel.py file the kernel should then in fact work with either python2 or 3).  
2. Apply the changes with a 'python setup.py install' from the command line. 
3. Now follow instructions for a [Stata Automation object](http://www.stata.com/automation/#createmsapp) (I used instructions for a Vista machine).
4. From the command line type 'ipython notebook' (or 'jupyter notebook') . You'll see Stata open up in the background when you open your first notebook.

Thanks for this kernel, This is huge!

One remaining question:  what about plots? They don't seem to show up either in the notebook or in the parallel Stata session.

**Comment by jrfiedler** [comment]
Sorry for the delay. I probably should have put on the README that this was pretty experimental. I honestly didn't expect anyone to be using it yet.

I'll look over the pull request. Thanks for finding the problem.

**Comment by jrfiedler** [comment]
> what about plots?

I haven't tried doing anything with plots yet. I believe Stata's plot windows are automatically hidden when Stata is being automated. One way to get graphs would be to insert a command into Stata to save the graph, then use Python code to insert the saved graph into the cell. I did something like that for a demo at the 2014 Stata Conference ([pdf of presentation](http://www.stata.com/meeting/boston14/abstracts/materials/boston14-fiedler.pdf)--see pages 30-36; code [here](https://github.com/jrfiedler/StataCon2014), and more specifically [here](https://github.com/jrfiedler/StataCon2014/blob/master/stata_interface.py)).

Hopefully I will have some time to work on plots soon.

**Comment by jrfiedler** [comment]
**methodds**, I see you forked the repo and made the change in your fork, but did you do a pull request? I don't see any.

**Comment by cschwem2er** [comment]
Hi, 
you should have received a PR now. I also added @jhconning  's suggestion for the future import. As for the plotting issue, maybe you could have a look at the solution in ipystata https://github.com/TiesdeKok/ipystata/issues/4

On a sidenote: although this might not be the best place to discuss this, but maybe working together with ipystata and @TiesdeKok would be a good idea anyway. Isn't it possible to combine your two approaches, so that one could choose between "stata only"  mode and cell magics? This would be such a huge possibility for modern Stata use.

**Comment by jrfiedler** [comment]
Fixed in [this pull request](https://github.com/jrfiedler/stata-kernel/pull/2) and subsequent commit 673d57faa4bc70650b3ee957e4e639aa5fa10de0
